### ISSUE TITLE
use a template

### ISSUE THREAD

**Issue by eylles** [valeriy-w/Obwal#1]
you know, you could have just made a template like so:

obsidian.css
```css
/* CSS variables   Generated by 'wal' */

:root{{
    --color0:  {color0};
    --color1:  {color1};
    --color2:  {color2};
    --color3:  {color3};
    --color4:  {color4};
    --color5:  {color5};
    --color6:  {color6};
    --color7:  {color7};
    --color8:  {color8};
    --color9:  {color9};
    --color10: {color10};
    --color11: {color11};
    --color12: {color12};
    --color13: {color13};
    --color14: {color14};
    --color15: {color15};
}}

.theme-dark {{
    --color-base-00: var(--color0); /* Фон */
    --color-base-20: none;
    --color-base-30: none;
}}

body.theme-dark {{
    color: var(--color7);
}}

.cm-header {{
    color: var(--color3);
}}

.workspace-tab-header-container {{
    background-color: var(--background);
}}


.side-dock-ribbon-action {{
    color: var(--color9);
}}
```

then on your install script copy the template to `$XDG_CONFIG_HOME/wal/templates/`, which will put the generated css file in `$XDG_CACHE_HOME/wal/`

wal has for quite a while had the option `-o` which runs a script specified by path after wal is done exporting all integrated and user templates, you can have that script be something like this:

postrun.sh
```sh
#!/bin/sh

myname="${0##*/}"

# usage: prettyp "$1" "$2"
# result: [1] 2: 3
prettyp() {
    printf '[\033[1;32m%s\033[0m] %s\n' "$1" "$2"
}

obsidian_snippets_dir="${HOME}/.obsidian/snippets"

my_config="${XDG_CONFIG_HOME}/wal/postrun.rc"

if [ -f "$my_config" ]; then
    . "$my_config"
fi

cp -f "$XDG_CACHE_HOME/wal/obsidian.css" "$obsidian_snippets_dir/obsidian.css"

prettyp "$myname" "obsidiad.css updated"
```

now users can specify their obsidian snippets dir inside `$XDG_CONFIG_HOME/wal/postrun.rc` like this:
```sh
obsidian_snippets_dir="my/obsidian/directory"
```
and put it in `$XDG_CONFIG_HOME/wal/postrun.sh`

now simply run wal like this `wal -i 'path/to/my/cool/image.png' -o "$XDG_CONFIG_HOME/wal/postrun.sh"`

and it will always run the script to copy the obsidian css to the correct place.

that works with both the old pywal from dylan as well as the maintained fork [pywal16](https://github.com/eylles/pywal16) without needing to modify any python code.
